data/profiles.json

Added leekelleher to profiles.json

---

data/profiles.json

Added my connection details, I hope I have done it right!

Update profiles.json by Adam Shallcross

---

data/profiles.json

Add Nik Rimington profile

---

data/profiles.json

Added profile for Aaron Sadler

Aaron sadler uk patch 1

---

data/profiles.json

Add my profile

---

data/profiles.json

Added lil' ol' me

---

data/profiles.json

Added myself 🙂

---

data/profiles.json

Got my stupid website URL wrong

---

data/profiles.json

Added profile for Limbo

---

data/profiles.json

Adds Warren

---

data/profiles.json

Predicted url for 24 days, let’s hope I’m right!
Doing it today as it’ll be published over the weekend when I’m not about

Add Joe Glombek BSky and 24 days

---

data/profiles.json

Added Dean Leigh

---

data/profiles.json

Correct Joe Glombek 24 Days link

---

data/profiles.json

Added profile: yinzy00

---

data/profiles.json

Adding 24 days article

---

data/profiles.json

Add 24 days blog (2023)

---

data/profiles.json

Add profile: liamgold

---

data/profiles.json

Add 24days blog 2024

---

data/profiles.json

Adding Matt Bliss profile

---

data/profiles.json

- [x ] I have checked all URL's are valid and correct
- [x ] All URLs are free of any unnecessary query parameters
- [x ] All URLs are free of any unnecessary trailing slashes
- [x ] Added entries are in alphabetical order by `alias`
- [x ] Avatar fields point to a valid image URL

Add profile Johan Reitsma
